- README.md
> Removing merge conflict info

- datasources/Wikidata/queries/chemicalAllPrimary.rq
- datasources/Wikidata/queries/geneproteinHumanAllPrimary.rq
- datasources/Wikidata/queries/geneproteinHumanRedirects.rq
@tabbassidaloii 
See changes to geneprotein queries to include only human entries.
Also added query for primary IDs for chemicals.
Still need to add the synonyms ass optional in the statements for both geneprotein and chemicals.
> Wikidata queries de sl

- datasources/Wikidata/queries/geneHumanRedirects.rq
Updating query which is almost always timing out @tabbassidaloii  I'll add a separate query for the protein secondary IDs, and than merge the data using bash
> Update and rename geneproteinHumanRedirects.rq to geneHumanRedirects.rq

- .github/workflows/chebi.yml
Posts an issue with the new date and @tabbassidaloii as assignee
> Added post-issue step

- .github/workflows/wikidata.yml
> Added post issue step to wikidata workflow

- .github/workflows/chebi.yml
> Removed conflictive line for ChEBI action

- .github/workflows/chebi.yml
- datasources/chebi/config
- datasources/hmdb/config
- datasources/ncbi/config
- datasources/uniprot/config
- datasources/wikidata/config
Implements the changes discussed:
- Retrieves the current version from Zenodo
- Compares against the latest version, if different
- Creates issue detailing changes
- If the script used to process the data fails, creates issue reporting the error
> ChEBI release check and test workflow

- .github/workflows/chebi.yml
The action was failing with message:
```Run datasources/chebi/config .
/home/runner/work/_temp/0fe5505b-a55e-4fca-b749-a4b2b0d01317.sh: line 1: datasources/chebi/config: Permission denied```
> Try to debug failed config file access

- .github/workflows/chebi.yml
- .github/workflows/hgnc.yml
- .github/workflows/ncbi.yml
Avoid posting issues if there are no changes (solves #92)
For HMDB: included in https://github.com/sec2pri/mapping_preprocessing/pull/98
> Added if clause to workflows (ChEBI, HGNC, NCBI)

- .github/ISSUE_TEMPLATE/ISSUE_FAIL.md
- .github/ISSUE_TEMPLATE/ISSUE_UPDATE.md
- .github/workflows/chebi.yml
- .github/workflows/hgnc.yml
- .github/workflows/hmdb.yml
- .github/workflows/ncbi.yml
> Retrieve processed files as artifacts

- .github/workflows/chebi.yml
- .github/workflows/hgnc.yml
- .github/workflows/hmdb.yml
- .github/workflows/ncbi.yml
- Removes unnecessary echoes from the diff step
- Improves readability of the diff step log, to see at a glance which pairs have changed
> Remove unnecessary diff workflow echoes

- .github/ISSUE_TEMPLATE/ISSUE_UPDATE.md
- .github/workflows/chebi.yml
- .github/workflows/hgnc.yml
- .github/workflows/hmdb.yml
- .github/workflows/ncbi.yml
Retrieves the BridgeDB regex patterns for each datasource and checks for the integrity of the IDs and also reports on the % of changes defined as (# of mapping pairs changed)/(total lines of mapping pairs in current data version)
> QC for new release identifiers, report which % of the ID pairs has changed

- .github/workflows/wikidata.yml
> Commented out all Wikidata queries except 1

- .github/workflows/wikidata.yml
- datasources/wikidata/queries/chemicalRedirects.rq
Still need to update the curl command
> Changed to qlever compatible

- .github/workflows/wikidata.yml
> Another checkout V4 update

- .github/workflows/maven.yml
Updating to version 4 as well
@jmillanacosta Please check my update :)
> checkout action update to version 4

- .github/workflows/uniprot.yml
> Bump upload-artifacts to v4

- .github/workflows/hmdb.yml
> Bump upload-artifact to v4

- .github/workflows/wikidata.yml
@jmillanacosta 
After job has run successfully, please integrate :)
> Fixed Qlever URL

- datasources/wikidata/queries/geneHumanRedirects.rq
> Qlever compatible gene Query

- .github/workflows/wikidata.yml
> dded gene and protein runs from QLever

- .github/workflows/contentStats.yml
> Added HGNC content counts

- .github/workflows/hgnc.yml
Changed from FTP to ttps://storage.googleapis.com/public-download-files/hgnc/archive/archive/quarterly/tsv/
> Update download URLs for HMDB

- .github/workflows/hgnc.yml
* Update to the new download URLs for HMDB
* Bump upload-artifact
* Let the release page load js
* Fix puppeteer issue
> Update download URLs for HMDB (#162)

- .github/workflows/wikidata.yml
work in progress to align with existing jobs
> Adding data processing in again

- .github/workflows/contentStats.yml
> Added UniProt counts

- .github/workflows/wikidata.yml
> Removing questionmark in column headers

- .github/workflows/wikidata.yml
- datasources/wikidata/queries/geneHumanAllRedirects.rq
- datasources/wikidata/queries/proteinHumanAllRedirects.rq
@tabbassidaloii these fixes should resolve most of the requests as posted here https://github.com/sec2pri/mapping_preprocessing/issues/175
> Denise sl22 patch 2

- .github/workflows/chebi.yml
- .github/workflows/hgnc.yml
- .github/workflows/hmdb.yml
- .github/workflows/ncbi.yml
- .github/workflows/uniprot.yml
- .github/workflows/wikidata.yml
> Denise sl22 no.zip.zip

- .github/workflows/sssom2rdf.yml
- datasources/hgnc/mappings/README.md
- datasources/hmdb/mappings/README.md
- datasources/ncbi/mappings/README.md
- datasources/uniprot/mappings/README.md
- datasources/wikidata/mappings/README.md
@tabbassidaloii : when the PREFIXes in the SSSOM file are added between quotation marks, the SSOM files are valid and the rest of the workflow is green!
> Sssom2 rdf all data
